language: generic
install: skip

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      sudo: required
      script: ./build-docker.sh

    - os: osx
      language: cpp
      script: ./build-macos.sh

    - os: windows
      language: cpp
      script: ./build-windows.bat
