linux:
	g++ test.cpp  -I ../dist/crashpad-Linux/include/ -I ../dist/crashpad-Linux/include/mini_chromium/ --std=c++11 -L ../dist/crashpad-Linux/lib -Wl,--start-group -lutil  -lbase -lclient -Wl,--end-group -D_GLIBCXX_USE_CXX11_ABI=0
