parameters:
  arch: ""

jobs:
  - job: crashpad_windows_${{ parameters.arch }}
    displayName: Crashpad (Windows, ${{ parameters.arch }})
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: prescript-common.yml
      - bash: |
          make build-windows-all -C crashpad
          grep -ir '/MT' .
          grep -ir '/MD' .
          grep -ir 'multithread' .
        env:
          BUILD_ARCH: "${{ parameters.arch }}"
      - template: zeus-upload.yml
        parameters:
          path: ./crashpad/dist/out
          pattern: "*.zip"
          uploadName: "crashpad-Windows-${{ parameters.arch }}.zip"
      - template: zeus-report.yml
