jobs:
  # MacOS
  - job: breakpad_macos
    displayName: Breakpad (MacOS, x86_64)
    pool:
      vmImage: "macos-10.13"
    steps:
      - template: prescript-common.yml
      - bash: |
          set -eux
          cd breakpad/
          make build-macos-all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "breakpad/macos/dist/out/breakpad-Darwin.zip"
      - template: zeus-upload.yml
        parameters:
          path: ./breakpad/dist
          pattern: "*.zip"
          uploadName: "breakpad-Darwin-x86_64.zip"
      - template: zeus-report.yml

  # Linux
  - job: breakpad_linux
    displayName: Breakpad (Linux, x86_64)
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - template: prescript-common.yml
      - bash: |
          set -eux
          cd breakpad/
          make build-linux-docker-all
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "breakpad/linux/dist/out/breakpad-Linux.zip"
      - template: zeus-upload.yml
        parameters:
          path: ./breakpad/dist
          pattern: "*.zip"
          uploadName: "breakpad-Linux-x86_64.zip"
      - template: zeus-report.yml

  # Windows
  - template: build-breakpad-windows.yml
    parameters:
      arch: "i686"
  - template: build-breakpad-windows.yml
    parameters:
      arch: "x86_64"

  # Android
  - job: breakpad_android
    displayName: Breakpad (Android, all)
    pool:
      vmImage: "macos-10.13"
    steps:
      - template: prescript-common.yml
      - bash: |
          set -eux
          cd breakpad/
          make build-android-all
      - template: zeus-upload.yml
        parameters:
          path: ./breakpad/dist
          pattern: "*.zip"
          uploadName: "breakpad-Android-all.zip"
      - template: zeus-report.yml
